In [1]:
import numpy as np

L = np.random.random(100)

In [2]:
L

array([0.26535299, 0.19497709, 0.24004724, 0.13927855, 0.34909504,
       0.19793588, 0.27338369, 0.26649199, 0.1517676 , 0.10071484,
       0.60331477, 0.23992556, 0.05254053, 0.65551818, 0.04873768,
       0.24523866, 0.93189327, 0.52964581, 0.80174106, 0.55657322,
       0.01859699, 0.29540466, 0.70479009, 0.50669051, 0.4187927 ,
       0.55799676, 0.54109965, 0.82048932, 0.74286369, 0.87173769,
       0.45871733, 0.08060437, 0.2884917 , 0.86064233, 0.86383292,
       0.45153595, 0.1869466 , 0.81173874, 0.53795924, 0.77230596,
       0.66495748, 0.48001601, 0.73130926, 0.64790319, 0.23115561,
       0.5338962 , 0.06124512, 0.8124394 , 0.30794828, 0.26491361,
       0.41390535, 0.5511492 , 0.41709838, 0.53815198, 0.94238869,
       0.30094172, 0.54067981, 0.39596704, 0.58942335, 0.02353967,
       0.17932388, 0.78951766, 0.75151536, 0.0247384 , 0.32768124,
       0.25385466, 0.80000385, 0.53297101, 0.10178409, 0.3532209 ,
       0.45353902, 0.30131127, 0.62822037, 0.41874194, 0.37850

In [3]:
sum(L)

45.02815071210836

In [4]:
np.sum(L)

45.028150712108385

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

136 ms ± 4.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.25 ms ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

1.316119703220764e-07

In [7]:
np.max(big_array)

0.9999984070620723

In [8]:
big_array.min()

1.316119703220764e-07

In [9]:
big_array.max()

0.9999984070620723

In [10]:
big_array.sum()

500048.2375876238

In [20]:
X = np.arange(16, dtype='int64').reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int64)

In [21]:
np.sum(X)

120

In [22]:
np.sum(X, axis=0)

array([24, 28, 32, 36], dtype=int64)

In [23]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54], dtype=int64)

In [24]:
# 所有元素乘积
np.prod(X)

0

In [25]:
np.prod(X + 1)

20922789888000

In [27]:
# 求平均值
np.mean(X)

7.5

In [28]:
# 求中位数
np.median(X)

7.5

In [29]:
# 均值会对偏移太大的点很敏感
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [30]:
np.median(v)

2.0

In [33]:
# 取50%的数小于这个值
np.percentile(big_array, q=50)

0.4998973322996301

In [32]:
np.median(big_array)

0.4998973322996301

In [34]:
np.percentile(big_array, q=100)

0.9999984070620723

In [35]:
np.max(big_array)

0.9999984070620723

In [36]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.316119703220764e-07
0.2497880537441061
0.4998973322996301
0.7503398590308228
0.9999984070620723


In [37]:
# 方差
np.var(big_array)

0.08336686253661266

In [40]:
# 标准差
np.std(big_array)

0.2887332030380515

In [42]:
# 取100万个，均值为0，方差为1的正态分布
x = np.random.normal(0, 1, size=1000000)

In [43]:
np.mean(x)

0.0017880920846506053

In [44]:
np.std(x)

0.999708353626159

# 索引

In [45]:
np.min(x)

-4.824138249132655

In [48]:
# 最小值对应的索引值
np.argmin(x)

86033

In [49]:
x[86033]

-4.824138249132655

In [50]:
np.argmax(x)

317096

In [51]:
x[317096]

4.471550484505033

In [52]:
np.max(x)

4.471550484505033

# 排序和使用索引

In [53]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
np.random.shuffle(x)
x

array([ 7,  8, 11, 15,  4,  5, 10,  1,  6,  3, 12, 13, 14,  2,  0,  9])

In [55]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
x

array([ 7,  8, 11, 15,  4,  5, 10,  1,  6,  3, 12, 13, 14,  2,  0,  9])

In [57]:
x.sort()

In [58]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
X = np.random.randint(10, size=(4, 4))
X

array([[6, 4, 1, 2],
       [1, 7, 2, 8],
       [8, 8, 2, 8],
       [8, 2, 4, 1]])

In [60]:
np.sort(X)

array([[1, 2, 4, 6],
       [1, 2, 7, 8],
       [2, 8, 8, 8],
       [1, 2, 4, 8]])

In [61]:
np.sort(X, axis=1)

array([[1, 2, 4, 6],
       [1, 2, 7, 8],
       [2, 8, 8, 8],
       [1, 2, 4, 8]])

In [62]:
np.sort(X, axis=0)

array([[1, 2, 1, 1],
       [6, 4, 2, 2],
       [8, 7, 2, 8],
       [8, 8, 4, 8]])

In [63]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
np.random.shuffle(x)

In [65]:
x

array([12,  1, 11,  8,  9,  6,  2, 15,  4,  5, 13,  3,  7, 14,  0, 10])

In [66]:
# 第一小的数字在数组的第14个位置（0开头）
np.argsort(x)

array([14,  1,  6, 11,  8,  9,  5, 12,  3,  4, 15,  2,  0, 10, 13,  7],
      dtype=int64)

In [68]:
# 3前面的数字都比3要小，3后面的数字都比3要大
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6, 10,  9,  8, 11,  7, 12, 14, 13, 15])

In [69]:
# 比3小的数字的索引，和比3大的数字的索引
np.argpartition(x, 3)

array([14,  1,  6, 11,  8,  9,  5, 15,  4,  3,  2, 12,  0, 13, 10,  7],
      dtype=int64)

In [70]:
X

array([[6, 4, 1, 2],
       [1, 7, 2, 8],
       [8, 8, 2, 8],
       [8, 2, 4, 1]])

In [71]:
# 按行进行排序，里面都是索引
np.argsort(X, axis=1)

array([[2, 3, 1, 0],
       [0, 2, 1, 3],
       [2, 0, 1, 3],
       [3, 1, 2, 0]], dtype=int64)

In [72]:
np.argsort(X, axis=0)

array([[1, 3, 0, 3],
       [0, 0, 1, 0],
       [2, 1, 2, 1],
       [3, 2, 3, 2]], dtype=int64)

In [74]:
# 每行，比2小的放前面，比2大的放后面
np.argpartition(X, 2, axis=1)

array([[2, 3, 1, 0],
       [0, 2, 1, 3],
       [2, 1, 0, 3],
       [3, 1, 2, 0]], dtype=int64)

In [75]:
np.argpartition(X, 2, axis=0)

array([[1, 3, 0, 3],
       [0, 0, 1, 0],
       [2, 1, 2, 2],
       [3, 2, 3, 1]], dtype=int64)