In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

# train_test_split

In [6]:
shuffle_indexes = np.random.permutation(len(X))

In [7]:
shuffle_indexes

array([ 15,  54, 145,  58,  55,  71, 120, 113,  11,   2, 138,  33,  19,
       139,  57,  68,  91,  45,  31,  61,  50,   8,  48,  17, 132,  44,
        29,  47, 100,  66,  38,  59,  12, 104, 123, 141,  51, 124,  26,
       127, 119,  21,  42, 118,  41,  62,  24,  96,  73,  37,  85, 135,
        25,  82,  64,  75,  95,  52, 146,   9,  92, 128,  97, 107,  70,
        69, 111, 108,  98,  77, 116,  22, 103, 129, 122,  10,  27,   5,
        60, 102,   1, 121, 134,  14,   7,  23,  46, 140,  81, 110,  76,
       142,  36,  56, 131, 109,  53,  43, 114, 137,  88,  99,  72,  28,
       144,   6, 115, 112,  32, 148, 143, 130,  84,  39,   3,  89,  83,
       106,  35, 125,  20,  40,  16, 133,  49,  65, 101,   4,  86,  67,
        30, 126, 136,  13, 147,  74,  87,  93,  90, 149,  79,  80,  18,
         0, 105,  34,  94,  63,  78, 117])

In [8]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [9]:
test_size

30

In [10]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


# 使用我们的算法

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [19]:
from playML.kNN import KNNClassifier

In [20]:
my_knn_clf = KNNClassifier(k=3)

In [21]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [23]:
y_predict = my_knn_clf.predict(X_test)

In [24]:
y_predict

array([0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2,
       1, 2, 1, 0, 1, 2, 2, 0])

In [25]:
y_test

array([0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2,
       1, 2, 1, 0, 1, 2, 2, 0])

In [26]:
sum(y_predict == y_test)

30

In [27]:
sum(y_predict == y_test) / len(y_test)

1.0

# sklearn中的train_test_split

In [28]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [34]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [35]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
